configfile : "config/config.yaml"

module get_gisaid:
    snakefile:
        github(
            "jsbrittain/snakeshack",
            path="workflows/OxfordPhyloGenetics/sources/get_remote_file/workflow/Snakefile",
            branch="main",
        )
    config: config

use rule * from get_gisaid as get_gisaid_*
