configfile: "config/config.yaml"

module sleep2_a:
    snakefile:
        eval(
            f'{config["sleep2_a"]["snakefile"]["function"]}'
            '(*config["sleep2_a"]["snakefile"]["args"],'
            '**config["sleep2_a"]["snakefile"]["kwargs"])'
        )
    config:
        config["sleep2_a"]["config"]
use rule * from sleep2_a as sleep2_a_*

module sleep2_b:
    snakefile:
        eval(
            f'{config["sleep2_b"]["snakefile"]["function"]}'
            '(*config["sleep2_b"]["snakefile"]["args"],'
            '**config["sleep2_b"]["snakefile"]["kwargs"])'
        )
    config:
        config["sleep2_b"]["config"]
use rule * from sleep2_b as sleep2_b_*

module sleep2_c:
    snakefile:
        eval(
            f'{config["sleep2_c"]["snakefile"]["function"]}'
            '(*config["sleep2_c"]["snakefile"]["args"],'
            '**config["sleep2_c"]["snakefile"]["kwargs"])'
        )
    config:
        config["sleep2_c"]["config"]
use rule * from sleep2_c as sleep2_c_*

