configfile: "config/config.yaml"

rule gisaid:
    input:
        expand(
            "results/{indir}/{infile}",
            indir=config["input_namespace"],
            infile=config["input_filename"],
        ),
    output:
        expand(
            "results/{outdir}/{outfile}",
            outdir=config["output_namespace"],
            outfile=config["output_filename"],
        ),
    log:
        expand(
            "logs/{outdir}.log",
            outdir=config["output_namespace"],
        )
    benchmark:
        "benchmarks/gisaid.txt"
    conda:
        "envs/gisaid.yaml"
    shell:
        "workflow/scripts/gisaid_preprocess/process_gisaid_metadata.R {input} --outfile {output}"
