configfile: "config/config.yaml"

rule {{template}}:
    input:
        expand(
            "results/{indir}/{infile}",
            indir=config["input_namespace"],
            infile=config["input_filename"],
        ),
    output:
        expand(
            "results/{outdir}/{outfile}",
            outdir=config["output_namespace"],
            outfile=config["output_filename"],
        ),
    log:
        expand(
            "logs/{outdir}.log",
            outdir=config["output_namespace"],
        )
    benchmark:
        "benchmarks/{{template}}.txt"
    conda:
        "envs/conda.yaml"
    shell:
        "touch {output}"
