configfile: "config/config.yaml"

rule all:
    input:
        "results/oxfordphylogenetics/sleep1_out/mark",
        "results/oxfordphylogenetics/sleep2_out/mark",
        "results/oxfordphylogenetics/sleep3_out/mark",
    default_target: True

module oxfordphylogenetics_sleep1:
    snakefile:
        "../../snakeshack/workflows/OxfordPhyloGenetics/modules/sleep"
    config: config["oxfordphylogenetics/sleep1"]
use rule * from oxfordphylogenetics/sleep1 as oxfordphylogenetics/sleep1_*

module oxfordphylogenetics-sleep2:
    snakefile:
        "../../snakeshack/workflows/OxfordPhyloGenetics/modules/sleep"
    config: config["oxfordphylogenetics/sleep2"]
use rule * from oxfordphylogenetics/sleep2 as oxfordphylogenetics/sleep2_*

module oxfordphylogenetics-sleep3:
    snakefile:
        "../../snakeshack/workflows/OxfordPhyloGenetics/modules/sleep"
    config: config["oxfordphylogenetics/sleep3"]
use rule * from oxfordphylogenetics/sleep3 as oxfordphylogenetics/sleep3_*

