configfile: "config/config.yaml"

rule sleep:
    input:
        expand(
            "results/{indir}/{infile}",
            indir=config["input_namespace"],
            infile=config["input_filename"],
        ),
    output:
        expand(
            "results/{outdir}/{outfile}",
            outdir=config["output_namespace"],
            outfile=config["output_filename"],
        ),
    params:
        outdir=config["output_namespace"],
    log:
        "logs/{params.outdir}.log",
    benchmark:
        "benchmarks/{params.outdir}.txt"
    conda:
        "conda.yaml"
    shell:
        "sleep 1 && touch {output}"
