input_namespace:
  source1: source1
  source1_432026565: source1_432026565
  source1_930907771: source1_930907771
sleep1:
  config:
    input_filename: touch
    input_namespace: source1
    output_filename: touch
    output_namespace: sleep1
    sleeptime: 1
  snakefile:
    args:
    - jsbrittain/snakeshack
    function: github
    kwargs:
      branch: main
      path: workflows/Examples/modules/sleep/workflow/Snakefile
sleep1_1425581169:
  config:
    input_filename: touch
    input_namespace: source1_432026565
    output_filename: touch
    output_namespace: sleep1_1425581169
    sleeptime: 1
  snakefile:
    args:
    - jsbrittain/snakeshack
    function: github
    kwargs:
      branch: main
      path: workflows/Examples/modules/sleep/workflow/Snakefile
sleep1_1430884947:
  config:
    input_filename: touch
    input_namespace: source1_930907771
    output_filename: touch
    output_namespace: sleep1_1430884947
    sleeptime: 1
  snakefile:
    args:
    - jsbrittain/snakeshack
    function: github
    kwargs:
      branch: main
      path: workflows/Examples/modules/sleep/workflow/Snakefile
sleep2:
  config:
    input_filename: touch
    input_namespace: sleep1
    output_filename: touch
    output_namespace: sleep2
    sleeptime: 2
  snakefile:
    args:
    - jsbrittain/snakeshack
    function: github
    kwargs:
      branch: main
      path: workflows/Examples/modules/sleep/workflow/Snakefile
sleep2_1304487490:
  config:
    input_filename: touch
    input_namespace: sleep1_1430884947
    output_filename: touch
    output_namespace: sleep2_1304487490
    sleeptime: 2
  snakefile:
    args:
    - jsbrittain/snakeshack
    function: github
    kwargs:
      branch: main
      path: workflows/Examples/modules/sleep/workflow/Snakefile
sleep2_1308969523:
  config:
    input_filename: touch
    input_namespace: sleep1_1425581169
    output_filename: touch
    output_namespace: sleep2_1308969523
    sleeptime: 2
  snakefile:
    args:
    - jsbrittain/snakeshack
    function: github
    kwargs:
      branch: main
      path: workflows/Examples/modules/sleep/workflow/Snakefile
sleep3:
  config:
    input_filename: touch
    input_namespace: sleep2
    output_filename: touch
    output_namespace: sleep3
    sleeptime: 3
  snakefile:
    args:
    - jsbrittain/snakeshack
    function: github
    kwargs:
      branch: main
      path: workflows/Examples/modules/sleep/workflow/Snakefile
sleep3_397507604:
  config:
    input_filename: touch
    input_namespace: sleep2_1308969523
    output_filename: touch
    output_namespace: sleep3_397507604
    sleeptime: 3
  snakefile:
    args:
    - jsbrittain/snakeshack
    function: github
    kwargs:
      branch: main
      path: workflows/Examples/modules/sleep/workflow/Snakefile
sleep3_625048969:
  config:
    input_filename: touch
    input_namespace: sleep2_1304487490
    output_filename: touch
    output_namespace: sleep3_625048969
    sleeptime: 3
  snakefile:
    args:
    - jsbrittain/snakeshack
    function: github
    kwargs:
      branch: main
      path: workflows/Examples/modules/sleep/workflow/Snakefile
source1:
  config:
    input_namespace: ''
    output_filename: touch
    output_namespace: source1
  snakefile:
    args:
    - jsbrittain/snakeshack
    function: github
    kwargs:
      branch: main
      path: workflows/Examples/sources/touch/workflow/Snakefile
source1_432026565:
  config:
    input_namespace: ''
    output_filename: touch
    output_namespace: source1_432026565
  snakefile:
    args:
    - jsbrittain/snakeshack
    function: github
    kwargs:
      branch: main
      path: workflows/Examples/sources/touch/workflow/Snakefile
source1_930907771:
  config:
    input_namespace: ''
    output_filename: touch
    output_namespace: source1_930907771
  snakefile:
    args:
    - jsbrittain/snakeshack
    function: github
    kwargs:
      branch: main
      path: workflows/Examples/sources/touch/workflow/Snakefile
