input_namespace: source1
output_namespace: sleep3_413855814
sleep1:
  config:
    input_filename: touch
    input_namespace: source1
    output_filename: touch
    output_namespace: sleep1
    sleeptime: 1
  name: sleep1
  snakefile:
    args:
    - jsbrittain/snakeshack
    function: github
    kwargs:
      branch: main
      path: workflows/Examples/modules/sleep/config/config.yaml
  type: module
sleep1_1344616045:
  config:
    input_filename: touch
    input_namespace: source1_1295813483
    output_filename: touch
    output_namespace: sleep1_1344616045
    sleeptime: 1
  name: sleep1
  snakefile:
    args:
    - jsbrittain/snakeshack
    function: github
    kwargs:
      branch: main
      path: workflows/Examples/modules/sleep/config/config.yaml
  type: module
sleep1_2066875522:
  config:
    input_filename: touch
    input_namespace: source1_1489831665
    output_filename: touch
    output_namespace: sleep1_2066875522
    sleeptime: 1
  name: sleep1
  snakefile:
    args:
    - jsbrittain/snakeshack
    function: github
    kwargs:
      branch: main
      path: workflows/Examples/modules/sleep/config/config.yaml
  type: module
sleep2:
  config:
    input_filename: touch
    input_namespace: sleep1
    output_filename: touch
    output_namespace: sleep2
    sleeptime: 2
  name: sleep2
  snakefile:
    args:
    - jsbrittain/snakeshack
    function: github
    kwargs:
      branch: main
      path: workflows/Examples/modules/sleep/config/config.yaml
  type: module
sleep2_1216546917:
  config:
    input_filename: touch
    input_namespace: sleep1_1344616045
    output_filename: touch
    output_namespace: sleep2_1216546917
    sleeptime: 2
  name: sleep2
  snakefile:
    args:
    - jsbrittain/snakeshack
    function: github
    kwargs:
      branch: main
      path: workflows/Examples/modules/sleep/config/config.yaml
  type: module
sleep2_1342243708:
  config:
    input_filename: touch
    input_namespace: sleep1_2066875522
    output_filename: touch
    output_namespace: sleep2_1342243708
    sleeptime: 2
  name: sleep2
  snakefile:
    args:
    - jsbrittain/snakeshack
    function: github
    kwargs:
      branch: main
      path: workflows/Examples/modules/sleep/config/config.yaml
  type: module
sleep3:
  config:
    input_filename: touch
    input_namespace: sleep2
    output_filename: touch
    output_namespace: sleep3
    sleeptime: 3
  name: sleep3
  snakefile:
    args:
    - jsbrittain/snakeshack
    function: github
    kwargs:
      branch: main
      path: workflows/Examples/modules/sleep/config/config.yaml
  type: module
sleep3_1625775177:
  config:
    input_filename: touch
    input_namespace: sleep2_1216546917
    output_filename: touch
    output_namespace: sleep3_1625775177
    sleeptime: 3
  name: sleep3
  snakefile:
    args:
    - jsbrittain/snakeshack
    function: github
    kwargs:
      branch: main
      path: workflows/Examples/modules/sleep/config/config.yaml
  type: module
sleep3_413855814:
  config:
    input_filename: touch
    input_namespace: sleep2_1342243708
    output_filename: touch
    output_namespace: sleep3_413855814
    sleeptime: 3
  name: sleep3
  snakefile:
    args:
    - jsbrittain/snakeshack
    function: github
    kwargs:
      branch: main
      path: workflows/Examples/modules/sleep/config/config.yaml
  type: module
source1:
  config:
    input_namespace: null
    output_filename: touch
    output_namespace: source1
  name: source1
  snakefile:
    args:
    - jsbrittain/snakeshack
    function: github
    kwargs:
      branch: main
      path: workflows/Examples/sources/touch/config/config.yaml
  type: module
source1_1295813483:
  config:
    input_namespace: sleep3
    output_filename: touch
    output_namespace: source1_1295813483
  name: source1
  snakefile:
    args:
    - jsbrittain/snakeshack
    function: github
    kwargs:
      branch: main
      path: workflows/Examples/sources/touch/config/config.yaml
  type: module
source1_1489831665:
  config:
    input_namespace: sleep3_1625775177
    output_filename: touch
    output_namespace: source1_1489831665
  name: source1
  snakefile:
    args:
    - jsbrittain/snakeshack
    function: github
    kwargs:
      branch: main
      path: workflows/Examples/sources/touch/config/config.yaml
  type: module
