sleep1:
  config:
    input_filename: touch
    input_namespace: ''
    output_filename: touch
    output_namespace: sleep1_1232657818
    sleeptime: 1
  snakefile: ''
sleep2:
  config:
    input_filename: touch
    input_namespace: ''
    output_filename: touch
    output_namespace: sleep2_144412666
    sleeptime: 2
  snakefile: ''
sleep3:
  config:
    input_filename: touch
    input_namespace: ''
    output_filename: touch
    output_namespace: sleep3_1889307580
    sleeptime: 3
  snakefile: ''
source1:
  config:
    input_namespace: ''
    output_filename: touch
    output_namespace: source1_1394755113
  snakefile: ''
