configfile : "config/config.yaml"

rule nextalign:
    input:
        expand(
            "results/{indir}/{infile}",
            indir=config["input_namespace"],
            infile=config["input_filename"],
        ),
    output:
        expand(
            "results/{indir}/{infile}",
            indir=config["output_namespace"],
            infile=config["output_filename"],
        ),
    log:
        "logs/nextalign.log",
    benchmark:
        "benchmarks/nextalign.txt"
    conda:
        "envs/conda.yaml"
    shell:
        "workflow/scripts/run_nextalign.sh -i {input}"
