configfile: "config/config.yaml"

module sleep1:
    snakefile:
        eval(
            f'{config["sleep1"]["snakefile"]["function"]}'
            '(*config["sleep1"]["snakefile"]["args"],'
            '**config["sleep1"]["snakefile"]["kwargs"])'
        )
    config:
        config["sleep1"]["config"]
use rule * from sleep1 as sleep1_*

module sleep2:
    snakefile:
        eval(
            f'{config["sleep2"]["snakefile"]["function"]}'
            '(*config["sleep2"]["snakefile"]["args"],'
            '**config["sleep2"]["snakefile"]["kwargs"])'
        )
    config:
        config["sleep2"]["config"]
use rule * from sleep2 as sleep2_*

module sleep1_133346707:
    snakefile:
        eval(
            f'{config["sleep1_133346707"]["snakefile"]["function"]}'
            '(*config["sleep1_133346707"]["snakefile"]["args"],'
            '**config["sleep1_133346707"]["snakefile"]["kwargs"])'
        )
    config:
        config["sleep1_133346707"]["config"]
use rule * from sleep1_133346707 as sleep1_133346707_*

module sleep2_1162419788:
    snakefile:
        eval(
            f'{config["sleep2_1162419788"]["snakefile"]["function"]}'
            '(*config["sleep2_1162419788"]["snakefile"]["args"],'
            '**config["sleep2_1162419788"]["snakefile"]["kwargs"])'
        )
    config:
        config["sleep2_1162419788"]["config"]
use rule * from sleep2_1162419788 as sleep2_1162419788_*

module sleep1_733535296:
    snakefile:
        eval(
            f'{config["sleep1_733535296"]["snakefile"]["function"]}'
            '(*config["sleep1_733535296"]["snakefile"]["args"],'
            '**config["sleep1_733535296"]["snakefile"]["kwargs"])'
        )
    config:
        config["sleep1_733535296"]["config"]
use rule * from sleep1_733535296 as sleep1_733535296_*

module sleep2_1831829253:
    snakefile:
        eval(
            f'{config["sleep2_1831829253"]["snakefile"]["function"]}'
            '(*config["sleep2_1831829253"]["snakefile"]["args"],'
            '**config["sleep2_1831829253"]["snakefile"]["kwargs"])'
        )
    config:
        config["sleep2_1831829253"]["config"]
use rule * from sleep2_1831829253 as sleep2_1831829253_*

