configfile: "config/config.yaml"

rule init:
    output:
        expand(
            "results/{outdir}/{outfile}",
            outdir=config["output_namespace"],
            outfile=config["output_filename"],
        ),
    log:
        "logs/start.log",
    benchmark:
        "benchmarks/start.txt"
    conda:
        "envs/conda.yaml"
    shell:
        "touch {output}"
