input_namespace :
  gis : "gisaid_subsampled_seqs"
  owid : "processed_owid_case_data"
input_filename :
  gis : "gisaid_metadata.tsv"
  owid : "owid-covid-data.csv"
output_namespace : "subsample_gis_owid"
output_filename : "subsampled_gisaid_metadata.tsv"

subsampling :
  variant : "Delta"
  target_number_of_sequences : 5000
  start_month : "2020-08"
  end_month : "2021-08"
