configfile: "config/config.yaml"

rule copy:
    input:
        expand(
            "results/{indir}/{infile}",
            indir=config["input_namespace"],
            infile=config["input_filename"],
        ),
    output:
        expand(
            "results/{outdir}/{outfile}",
            outdir=config["output_namespace"],
            outfile=config["output_filename"],
        ),
    params:
        outdir=config["output_namespace"],
        filename=config["output_filename"],
    log:
        "logs/{params.indir}-connector_copy.log",
    benchmark:
        "benchmarks/{params.indir}-connector_copy.txt"
    conda:
        "envs/conda.yaml"
    shell:
        "cp -r * {input} {output}"
