input_namespace: {}
output_namespace: sleep3_c
sleep3_a:
  config:
    input_filename: touch
    input_namespace: null
    output_filename: touch
    output_namespace: sleep3_a
    sleep_time: 1
  name: sleep3_A
  snakefile: /Users/jsb/repos/jsbrittain/snakeshack/workflows/Examples/modules/sleep3l/workflow/Snakefile
  type: module
sleep3_b:
  config:
    input_filename: touch
    input_namespace: sleep3_a
    output_filename: touch
    output_namespace: sleep3_b
    sleep_time: 1
  name: sleep3_B
  snakefile: /Users/jsb/repos/jsbrittain/snakeshack/workflows/Examples/modules/sleep3l/workflow/Snakefile
  type: module
sleep3_c:
  config:
    input_filename: touch
    input_namespace: sleep3_b
    output_filename: touch
    output_namespace: sleep3_c
    sleep_time: 1
  name: sleep3_C
  snakefile: /Users/jsb/repos/jsbrittain/snakeshack/workflows/Examples/modules/sleep3l/workflow/Snakefile
  type: module
