configfile : "config/config.yaml"

rule process_owid_case_data:
    input:
        expand(
            "results/{outdir}/{infile}",
            outdir=config["input_namespace"],
            infile=config["input_filename"],
        ),
    output:
        expand(
            "results/{outdir}/{outfile}",
            outdir=config["output_namespace"],
            outfile=config["output_filename"],
        ),
    log:
        "logs/owid.log",
    benchmark:
        "benchmarks/owid.txt"
    params:
        cmd=workflow.source_path("scripts/process_owid_case_data.R")
    conda:
        "envs/conda.yaml"
    shell:
        "{params.cmd} {input} --outfile {output}"
