configfile : "config/config.yaml"

module get_reference_seqs:
    snakefile:
        github(
            "jsbrittain/snakeshack",
            path="workflows/OxfordPhyloGenetics/sources/get_remote_file/workflow/Snakefile",
            branch="main",
        )
    config: config

use rule * from get_reference_seqs as get_reference_seqs_*
