input_namespace: sleep2_a
output_namespace: sleep2_c
sleep2_a:
  config:
    input_filename: touch
    input_namespace: ''
    output_filename: touch
    output_namespace: sleep2_a
    sleep_time: 1
  name: sleep2_A
  snakefile:
    args:
    - jsbrittain/snakeshack
    function: github
    kwargs:
      branch: main
      path: workflows/Examples/modules/sleep2/workflow/Snakefile
  type: module
sleep2_b:
  config:
    input_filename: touch
    input_namespace: sleep2_a
    output_filename: touch
    output_namespace: sleep2_b
    sleep_time: 1
  name: sleep2_B
  snakefile:
    args:
    - jsbrittain/snakeshack
    function: github
    kwargs:
      branch: main
      path: workflows/Examples/modules/sleep2/workflow/Snakefile
  type: module
sleep2_c:
  config:
    input_filename: touch
    input_namespace: sleep2_b
    output_filename: touch
    output_namespace: sleep2_c
    sleep_time: 1
  name: sleep2_C
  snakefile:
    args:
    - jsbrittain/snakeshack
    function: github
    kwargs:
      branch: main
      path: workflows/Examples/modules/sleep2/workflow/Snakefile
  type: module
