configfile: "config/config.yaml"

module sleep1:
    snakefile:
        eval(
            f'{config["sleep1"]["snakefile"]["function"]}'
            '(*config["sleep1"]["snakefile"]["args"],'
            '**config["sleep1"]["snakefile"]["kwargs"])'
        )
    config:
        config["sleep1"]["config"]
use rule * from sleep1 as sleep1_*

module sleep2:
    snakefile:
        eval(
            f'{config["sleep2"]["snakefile"]["function"]}'
            '(*config["sleep2"]["snakefile"]["args"],'
            '**config["sleep2"]["snakefile"]["kwargs"])'
        )
    config:
        config["sleep2"]["config"]
use rule * from sleep2 as sleep2_*

module sleep3:
    snakefile:
        eval(
            f'{config["sleep3"]["snakefile"]["function"]}'
            '(*config["sleep3"]["snakefile"]["args"],'
            '**config["sleep3"]["snakefile"]["kwargs"])'
        )
    config:
        config["sleep3"]["config"]
use rule * from sleep3 as sleep3_*

module source1:
    snakefile:
        eval(
            f'{config["source1"]["snakefile"]["function"]}'
            '(*config["source1"]["snakefile"]["args"],'
            '**config["source1"]["snakefile"]["kwargs"])'
        )
    config:
        config["source1"]["config"]
use rule * from source1 as source1_*

