configfile: "config/config.yaml"

module sleep3_a:
    snakefile:
        eval(
            f'{config["sleep3_a"]["snakefile"]["function"]}'
            '(*config["sleep3_a"]["snakefile"]["args"],'
            '**config["sleep3_a"]["snakefile"]["kwargs"])'
        )
    config:
        config["sleep3_a"]["config"]
use rule * from sleep3_a as sleep3_a_*

module sleep3_b:
    snakefile:
        eval(
            f'{config["sleep3_b"]["snakefile"]["function"]}'
            '(*config["sleep3_b"]["snakefile"]["args"],'
            '**config["sleep3_b"]["snakefile"]["kwargs"])'
        )
    config:
        config["sleep3_b"]["config"]
use rule * from sleep3_b as sleep3_b_*

module sleep3_c:
    snakefile:
        eval(
            f'{config["sleep3_c"]["snakefile"]["function"]}'
            '(*config["sleep3_c"]["snakefile"]["args"],'
            '**config["sleep3_c"]["snakefile"]["kwargs"])'
        )
    config:
        config["sleep3_c"]["config"]
use rule * from sleep3_c as sleep3_c_*

