configfile: "config/config.yaml"

rule sleep:
    output:
        expand(
            "results/{outdir}{filename}",
            outdir=config["output_namespace"],
            filename=config["output_filename"],
        ),
    log:
        "logs/{params.outdir}{params.filename}.log",
    benchmark:
        "benchmarks/{params.outdir}{params.filename}.txt"
