configfile: "config/config.yaml"

rule start:
    output:
        expand(
            "results/{outdir}/{outfile}",
            outdir=config["output_namespace"],
            outfile=config["output_filename"],
        ),
    log:
        "logs/{params.outdir}.log",
    benchmark:
        "benchmarks/{params.outdir}.txt"
