configfile: "config/config.yaml"

module sleep1:
    snakefile:
        eval(
            f'{config["sleep1"]["snakefile"]["function"]}'
            '(*config["sleep1"]["snakefile"]["args"],'
            '**config["sleep1"]["snakefile"]["kwargs"])'
        )
    config:
        config["sleep1"]["config"]
use rule * from sleep1 as sleep1_*

module sleep2:
    snakefile:
        eval(
            f'{config["sleep2"]["snakefile"]["function"]}'
            '(*config["sleep2"]["snakefile"]["args"],'
            '**config["sleep2"]["snakefile"]["kwargs"])'
        )
    config:
        config["sleep2"]["config"]
use rule * from sleep2 as sleep2_*

