"""
Filter a comma or tab separated file based on filter settings

This version is specialised for use in the GRAPEVNE
BuilderTutorial project workflow.

Params:
    Source (string): Input filename
    Filters:
        Country code (string): International country code
"""
configfile: "config/config.yaml"
from snakemake.remote import AUTO
import json

indir = config["input_namespace"]
outdir = config["output_namespace"]
params = config["params"]

def resource(filename):
    try:
        return AUTO.remote(srcdir(filename))
    except TypeError:
        return srcdir(filename)

rule target:
    input:
        source=expand(
            "results/{indir}/{filename}",
            indir=indir,
            filename=params["Source"],
        ),
        script=resource("../resources/scripts/filter.py"),
    output:
        expand(
            "results/{outdir}/{filename}",
            outdir=outdir,
            filename=params["Source"],
        ),
    log:
        "logs/test.log"
    params:
        filters=json.dumps(params["Filters"]).replace("\"", "\'"),
    conda:
        "envs/conda.yaml"
    shell:
        """
        python {input.script} \
            --source="{input.source}" \
            --dest="{output}" \
            --filters="{params.filters}" \
        """
