sleep1:
  config:
    input_filename: touch
    input_namespace: ''
    output_filename: touch
    output_namespace: sleep1
    sleeptime: 1
  snakefile:
    args:
    - jsbrittain/snakeshack
    function: github
    kwargs:
      branch: main
      path: workflows/Examples/modules/sleep/workflow/Snakefile
sleep2:
  config:
    input_filename: touch
    input_namespace: sleep1
    output_filename: touch
    output_namespace: sleep2
    sleeptime: 2
  snakefile:
    args:
    - jsbrittain/snakeshack
    function: github
    kwargs:
      branch: main
      path: workflows/Examples/modules/sleep/workflow/Snakefile
