examples_sleep_1:
  config:
    input_filename: mark
    input_namespace: in
    output_filename: mark
    output_namespace: examples_sleep_1
    sleeptime: 1
  name: (Examples) Sleep_1
  snakefile: /Users/jsb/repos/jsbrittain/snakeshack/workflows/Examples/modules/sleep/workflow/Snakefile
  type: module
examples_sleep_3:
  config:
    input_filename: mark
    input_namespace: sleep2_2
    output_filename: mark
    output_namespace: examples_sleep_3
    sleeptime: 1
  name: (Examples) Sleep_3
  snakefile: /Users/jsb/repos/jsbrittain/snakeshack/workflows/Examples/modules/sleep/workflow/Snakefile
  type: module
input_namespace:
  examples_sleep_1$: in
output_namespace: examples_sleep_3
sleep1:
  config:
    input_filename: touch
    input_namespace: examples_sleep_1
    output_filename: touch
    output_namespace: sleep1
    sleeptime: 1
  name: sleep1
  snakefile: /Users/jsb/repos/jsbrittain/snakeshack/workflows/Examples/modules/sleep/workflow/Snakefile
  type: module
sleep1_1:
  config:
    input_filename: touch
    input_namespace: sleep2
    output_filename: touch
    output_namespace: sleep1_1
    sleeptime: 1
  name: sleep1_1
  snakefile: /Users/jsb/repos/jsbrittain/snakeshack/workflows/Examples/modules/sleep/workflow/Snakefile
  type: module
sleep1_2:
  config:
    input_filename: touch
    input_namespace: sleep2_1
    output_filename: touch
    output_namespace: sleep1_2
    sleeptime: 1
  name: sleep1_2
  snakefile: /Users/jsb/repos/jsbrittain/snakeshack/workflows/Examples/modules/sleep/workflow/Snakefile
  type: module
sleep2:
  config:
    input_filename: touch
    input_namespace: sleep1
    output_filename: touch
    output_namespace: sleep2
    sleeptime: 2
  name: sleep2
  snakefile: /Users/jsb/repos/jsbrittain/snakeshack/workflows/Examples/modules/sleep/workflow/Snakefile
  type: module
sleep2_1:
  config:
    input_filename: touch
    input_namespace: sleep1_1
    output_filename: touch
    output_namespace: sleep2_1
    sleeptime: 2
  name: sleep2_1
  snakefile: /Users/jsb/repos/jsbrittain/snakeshack/workflows/Examples/modules/sleep/workflow/Snakefile
  type: module
sleep2_2:
  config:
    input_filename: touch
    input_namespace: sleep1_2
    output_filename: touch
    output_namespace: sleep2_2
    sleeptime: 2
  name: sleep2_2
  snakefile: /Users/jsb/repos/jsbrittain/snakeshack/workflows/Examples/modules/sleep/workflow/Snakefile
  type: module
