input_namespace:
  sleep1$: in
output_namespace: sleep2_2
sleep1:
  config:
    input_filename: touch
    input_namespace: in
    output_filename: touch
    output_namespace: sleep1
    sleeptime: 1
  name: sleep1
  snakefile: /Users/jsb/repos/jsbrittain/snakeshack/workflows/Examples/modules/sleep/workflow/Snakefile
  type: module
sleep1_1:
  config:
    input_filename: touch
    input_namespace: sleep2
    output_filename: touch
    output_namespace: sleep1_1
    sleeptime: 1
  name: sleep1
  snakefile: /Users/jsb/repos/jsbrittain/snakeshack/workflows/Examples/modules/sleep/workflow/Snakefile
  type: module
sleep1_2:
  config:
    input_filename: touch
    input_namespace: sleep2_1
    output_filename: touch
    output_namespace: sleep1_2
    sleeptime: 1
  name: sleep1
  snakefile: /Users/jsb/repos/jsbrittain/snakeshack/workflows/Examples/modules/sleep/workflow/Snakefile
  type: module
sleep2:
  config:
    input_filename: touch
    input_namespace: sleep1
    output_filename: touch
    output_namespace: sleep2
    sleeptime: 2
  name: sleep2
  snakefile: /Users/jsb/repos/jsbrittain/snakeshack/workflows/Examples/modules/sleep/workflow/Snakefile
  type: module
sleep2_1:
  config:
    input_filename: touch
    input_namespace: sleep1_1
    output_filename: touch
    output_namespace: sleep2_1
    sleeptime: 2
  name: sleep2
  snakefile: /Users/jsb/repos/jsbrittain/snakeshack/workflows/Examples/modules/sleep/workflow/Snakefile
  type: module
sleep2_2:
  config:
    input_filename: touch
    input_namespace: sleep1_2
    output_filename: touch
    output_namespace: sleep2_2
    sleeptime: 2
  name: sleep2
  snakefile: /Users/jsb/repos/jsbrittain/snakeshack/workflows/Examples/modules/sleep/workflow/Snakefile
  type: module
