input_namespace:
  _sleep2_a: in
output_namespace: sleep2_c
sleep2_a:
  config:
    input_filename: touch
    input_namespace: in
    output_filename: touch
    output_namespace: sleep2_a
    sleep_time: 1
  name: sleep2_A
  snakefile: /Users/jsb/repos/jsbrittain/snakeshack/workflows/Examples/modules/sleep2l/workflow/Snakefile
  type: module
sleep2_b:
  config:
    input_filename: touch
    input_namespace: sleep2_a
    output_filename: touch
    output_namespace: sleep2_b
    sleep_time: 1
  name: sleep2_B
  snakefile: /Users/jsb/repos/jsbrittain/snakeshack/workflows/Examples/modules/sleep2l/workflow/Snakefile
  type: module
sleep2_c:
  config:
    input_filename: touch
    input_namespace: sleep2_b
    output_filename: touch
    output_namespace: sleep2_c
    sleep_time: 1
  name: sleep2_C
  snakefile: /Users/jsb/repos/jsbrittain/snakeshack/workflows/Examples/modules/sleep2l/workflow/Snakefile
  type: module
