sleep1:
  config:
    input_filename: touch
    input_namespace: source1
    output_filename: touch
    output_namespace: sleep1
    sleeptime: 1
  snakefile:
    args:
    - jsbrittain/snakeshack
    function: github
    kwargs:
      branch: main
      path: workflows/Examples/modules/sleep/workflow/Snakefile
sleep2:
  config:
    input_filename: touch
    input_namespace: sleep1
    output_filename: touch
    output_namespace: sleep2
    sleeptime: 2
  snakefile:
    args:
    - jsbrittain/snakeshack
    function: github
    kwargs:
      branch: main
      path: workflows/Examples/modules/sleep/workflow/Snakefile
sleep3:
  config:
    input_filename: touch
    input_namespace: sleep2
    output_filename: touch
    output_namespace: sleep3
    sleeptime: 3
  snakefile:
    args:
    - jsbrittain/snakeshack
    function: github
    kwargs:
      branch: main
      path: workflows/Examples/modules/sleep/workflow/Snakefile
source1:
  config:
    input_namespace: ''
    output_filename: touch
    output_namespace: source1
  snakefile:
    args:
    - jsbrittain/snakeshack
    function: github
    kwargs:
      branch: main
      path: workflows/Examples/sources/touch/workflow/Snakefile
