configfile: "config/config.yaml"

module source1:
    snakefile:
        config["source1"]["snakefile"]
    config:
        config["source1"]["config"]
use rule * from source1 as source1_*

module sleep1:
    snakefile:
        config["sleep1"]["snakefile"]
    config:
        config["sleep1"]["config"]
use rule * from sleep1 as sleep1_*

module sleep2:
    snakefile:
        config["sleep2"]["snakefile"]
    config:
        config["sleep2"]["config"]
use rule * from sleep2 as sleep2_*

module sleep3:
    snakefile:
        config["sleep3"]["snakefile"]
    config:
        config["sleep3"]["config"]
use rule * from sleep3 as sleep3_*

module source1_1601477087:
    snakefile:
        config["source1_1601477087"]["snakefile"]
    config:
        config["source1_1601477087"]["config"]
use rule * from source1_1601477087 as source1_1601477087_*

module sleep1_61027547:
    snakefile:
        config["sleep1_61027547"]["snakefile"]
    config:
        config["sleep1_61027547"]["config"]
use rule * from sleep1_61027547 as sleep1_61027547_*

module sleep2_669144788:
    snakefile:
        config["sleep2_669144788"]["snakefile"]
    config:
        config["sleep2_669144788"]["config"]
use rule * from sleep2_669144788 as sleep2_669144788_*

module sleep3_1128200094:
    snakefile:
        config["sleep3_1128200094"]["snakefile"]
    config:
        config["sleep3_1128200094"]["config"]
use rule * from sleep3_1128200094 as sleep3_1128200094_*

module source1_2127782518:
    snakefile:
        config["source1_2127782518"]["snakefile"]
    config:
        config["source1_2127782518"]["config"]
use rule * from source1_2127782518 as source1_2127782518_*

module sleep1_1817413699:
    snakefile:
        config["sleep1_1817413699"]["snakefile"]
    config:
        config["sleep1_1817413699"]["config"]
use rule * from sleep1_1817413699 as sleep1_1817413699_*

module sleep2_627204990:
    snakefile:
        config["sleep2_627204990"]["snakefile"]
    config:
        config["sleep2_627204990"]["config"]
use rule * from sleep2_627204990 as sleep2_627204990_*

module sleep3_641955481:
    snakefile:
        config["sleep3_641955481"]["snakefile"]
    config:
        config["sleep3_641955481"]["config"]
use rule * from sleep3_641955481 as sleep3_641955481_*

