configfile: "config/config.yaml"

params = config["params"]

rule copy:
    output:
        expand(
            "results/{outdir}/{filename}",
            outdir=config["output_namespace"],
            filename=params["filename"],
        )
    conda:
        "envs/conda.yaml"
    shell:
        """
        touch {output}
        """
