configfile: "config/config.yaml"
from grapevne_helper import import_grapevne

grapevne = import_grapevne(workflow)
globals().update(vars(grapevne))

rule copy:
    output:
        outfile = output(params("filename")),
    shell:
        """
        touch {output.outfile}
        """
