configfile: "config/config.yaml"

rule copy:
    input:
        expand(
            "results/{indir}/{infile}",
            indir=config["input_namespace"],
            infile=config["input_filename"],
        ),
    output:
        expand(
            "results/{outdir}/{outfile}",
            outdir=config["output_namespace"],
            outfile=config["output_filename"],
        ),
    log:
        expand(
            "logs/{outdir}-connector_copy.log",
            outdir=config["output_namespace"],
        )
    benchmark:
        "benchmarks/copy.txt"
    conda:
        "envs/conda.yaml"
    shell:
        "cp -r {input} {output}"
