configfile: "config/config.yaml"

indir = config["input_namespace"]
outdir = config["output_namespace"]

rule random_subsample_ids_metadata:
    input:
        master_metadata = expand(
            "{master_metadata}",
            master_metadata=config["params"]["master_metadata"],
        )
    output:
        subsample_ids = expand(
            "results/{outdir}/s{{key}}/subsample_ids.tsv",
            outdir=config["output_namespace"]
        ),
        subsample_metadata = expand(
            "results/{outdir}/s{{key}}/subsample_metadata.tsv",
            outdir=config["output_namespace"]
        )
    params:
        n_random=config["params"]["n_random"],
    conda:
        "envs/conda.yaml"
    shell:
        """
        head -n1 {input.master_metadata} > {output.subsample_metadata} &&
        shuf -n {params.n_random} {input.master_metadata} >> {output.subsample_metadata} &&
        tail -n +2 {output.subsample_metadata} | cut -f1 > {output.subsample_ids}
        """

rule subsample_alignment:
    input:
        subsample_ids = expand(
            "results/{outdir}/s{{key}}/subsample_ids.tsv",
            indir=indir, outdir=outdir,
        )
    output:
        expand(
            "results/{outdir}/s{{key}}/subsample_aln.fasta",
            outdir=outdir,
        )
    params:
        master_fasta=config["params"]["master_fasta"]
    conda:
        "envs/conda.yaml"
    shell:
        """
        seqkit grep -n -f {input.subsample_ids} {params.master_fasta} > {output}
        """
