input_namespace: sleep1
output_namespace: sleep2_402186472
sleep1:
  config:
    input_filename: touch
    input_namespace: ''
    output_filename: touch
    output_namespace: sleep1
    sleeptime: 1
  snakefile:
    args:
    - jsbrittain/snakeshack
    function: github
    kwargs:
      branch: main
      path: workflows/Examples/modules/sleep/config/config.yaml
sleep1_1399554726:
  config:
    input_filename: touch
    input_namespace: sleep2
    output_filename: touch
    output_namespace: sleep1_1399554726
    sleeptime: 1
  snakefile:
    args:
    - jsbrittain/snakeshack
    function: github
    kwargs:
      branch: main
      path: workflows/Examples/modules/sleep/config/config.yaml
sleep1_899365717:
  config:
    input_filename: touch
    input_namespace: sleep2_1800568389
    output_filename: touch
    output_namespace: sleep1_899365717
    sleeptime: 1
  snakefile:
    args:
    - jsbrittain/snakeshack
    function: github
    kwargs:
      branch: main
      path: workflows/Examples/modules/sleep/config/config.yaml
sleep2:
  config:
    input_filename: touch
    input_namespace: sleep1
    output_filename: touch
    output_namespace: sleep2
    sleeptime: 2
  snakefile:
    args:
    - jsbrittain/snakeshack
    function: github
    kwargs:
      branch: main
      path: workflows/Examples/modules/sleep/config/config.yaml
sleep2_1800568389:
  config:
    input_filename: touch
    input_namespace: sleep1_1399554726
    output_filename: touch
    output_namespace: sleep2_1800568389
    sleeptime: 2
  snakefile:
    args:
    - jsbrittain/snakeshack
    function: github
    kwargs:
      branch: main
      path: workflows/Examples/modules/sleep/config/config.yaml
sleep2_402186472:
  config:
    input_filename: touch
    input_namespace: sleep1_899365717
    output_filename: touch
    output_namespace: sleep2_402186472
    sleeptime: 2
  snakefile:
    args:
    - jsbrittain/snakeshack
    function: github
    kwargs:
      branch: main
      path: workflows/Examples/modules/sleep/config/config.yaml
