input_namespace: sleep1
output_namespace: sleep2_1831829253
sleep1:
  config:
    input_filename: touch
    input_namespace: ''
    output_filename: touch
    output_namespace: sleep1
    sleeptime: 1
  name: sleep1
  snakefile:
    args:
    - jsbrittain/snakeshack
    function: github
    kwargs:
      branch: main
      path: workflows/Examples/modules/sleep/config/config.yaml
  type: module
sleep1_133346707:
  config:
    input_filename: touch
    input_namespace: sleep2
    output_filename: touch
    output_namespace: sleep1_133346707
    sleeptime: 1
  name: sleep1
  snakefile:
    args:
    - jsbrittain/snakeshack
    function: github
    kwargs:
      branch: main
      path: workflows/Examples/modules/sleep/config/config.yaml
  type: module
sleep1_733535296:
  config:
    input_filename: touch
    input_namespace: sleep2_1162419788
    output_filename: touch
    output_namespace: sleep1_733535296
    sleeptime: 1
  name: sleep1
  snakefile:
    args:
    - jsbrittain/snakeshack
    function: github
    kwargs:
      branch: main
      path: workflows/Examples/modules/sleep/config/config.yaml
  type: module
sleep2:
  config:
    input_filename: touch
    input_namespace: sleep1
    output_filename: touch
    output_namespace: sleep2
    sleeptime: 2
  name: sleep2
  snakefile:
    args:
    - jsbrittain/snakeshack
    function: github
    kwargs:
      branch: main
      path: workflows/Examples/modules/sleep/config/config.yaml
  type: module
sleep2_1162419788:
  config:
    input_filename: touch
    input_namespace: sleep1_133346707
    output_filename: touch
    output_namespace: sleep2_1162419788
    sleeptime: 2
  name: sleep2
  snakefile:
    args:
    - jsbrittain/snakeshack
    function: github
    kwargs:
      branch: main
      path: workflows/Examples/modules/sleep/config/config.yaml
  type: module
sleep2_1831829253:
  config:
    input_filename: touch
    input_namespace: sleep1_733535296
    output_filename: touch
    output_namespace: sleep2_1831829253
    sleeptime: 2
  name: sleep2
  snakefile:
    args:
    - jsbrittain/snakeshack
    function: github
    kwargs:
      branch: main
      path: workflows/Examples/modules/sleep/config/config.yaml
  type: module
