configfile: "config/config.yaml"

rule provide_seeds:
    input:
        "resources/seeds.txt"
    output:
        expand(
            "results/{outdir}/seeds.txt",
            outdir=config["output_namespace"],
        )
    conda:
        "envs/conda.yaml"
    shell:
        "cp resources/seeds.txt {output}"
