configfile: "config/config.yaml"

from snakemake.remote import AUTO

REMOTE_PATH = "https://github.com/jsbrittain/snakeshack/raw/main/workflows/vocpl/modules/provide_seeds"
function remote(filename)
    return AUTO.remote(path + "/" + filename)

rule provide_seeds:
    input:
        remote("resources/seeds.txt")
    output:
        expand(
            "results/{outdir}/seeds.txt",
            outdir=config["output_namespace"],
        )
    conda:
        "envs/conda.yaml"
    shell:
        "cp {input} {output}"
