configfile: "config/config.yaml"

module source1:
    snakefile:
        eval(
            f'{config["source1"]["snakefile"]["function"]}'
            '(*config["source1"]["snakefile"]["args"],'
            '**config["source1"]["snakefile"]["kwargs"])'
        )
    config:
        config["source1"]["config"]
use rule * from source1 as source1_*

module sleep1:
    snakefile:
        eval(
            f'{config["sleep1"]["snakefile"]["function"]}'
            '(*config["sleep1"]["snakefile"]["args"],'
            '**config["sleep1"]["snakefile"]["kwargs"])'
        )
    config:
        config["sleep1"]["config"]
use rule * from sleep1 as sleep1_*

module sleep2:
    snakefile:
        eval(
            f'{config["sleep2"]["snakefile"]["function"]}'
            '(*config["sleep2"]["snakefile"]["args"],'
            '**config["sleep2"]["snakefile"]["kwargs"])'
        )
    config:
        config["sleep2"]["config"]
use rule * from sleep2 as sleep2_*

module sleep3:
    snakefile:
        eval(
            f'{config["sleep3"]["snakefile"]["function"]}'
            '(*config["sleep3"]["snakefile"]["args"],'
            '**config["sleep3"]["snakefile"]["kwargs"])'
        )
    config:
        config["sleep3"]["config"]
use rule * from sleep3 as sleep3_*

module source1_1295813483:
    snakefile:
        eval(
            f'{config["source1_1295813483"]["snakefile"]["function"]}'
            '(*config["source1_1295813483"]["snakefile"]["args"],'
            '**config["source1_1295813483"]["snakefile"]["kwargs"])'
        )
    config:
        config["source1_1295813483"]["config"]
use rule * from source1_1295813483 as source1_1295813483_*

module sleep1_1344616045:
    snakefile:
        eval(
            f'{config["sleep1_1344616045"]["snakefile"]["function"]}'
            '(*config["sleep1_1344616045"]["snakefile"]["args"],'
            '**config["sleep1_1344616045"]["snakefile"]["kwargs"])'
        )
    config:
        config["sleep1_1344616045"]["config"]
use rule * from sleep1_1344616045 as sleep1_1344616045_*

module sleep2_1216546917:
    snakefile:
        eval(
            f'{config["sleep2_1216546917"]["snakefile"]["function"]}'
            '(*config["sleep2_1216546917"]["snakefile"]["args"],'
            '**config["sleep2_1216546917"]["snakefile"]["kwargs"])'
        )
    config:
        config["sleep2_1216546917"]["config"]
use rule * from sleep2_1216546917 as sleep2_1216546917_*

module sleep3_1625775177:
    snakefile:
        eval(
            f'{config["sleep3_1625775177"]["snakefile"]["function"]}'
            '(*config["sleep3_1625775177"]["snakefile"]["args"],'
            '**config["sleep3_1625775177"]["snakefile"]["kwargs"])'
        )
    config:
        config["sleep3_1625775177"]["config"]
use rule * from sleep3_1625775177 as sleep3_1625775177_*

module source1_1489831665:
    snakefile:
        eval(
            f'{config["source1_1489831665"]["snakefile"]["function"]}'
            '(*config["source1_1489831665"]["snakefile"]["args"],'
            '**config["source1_1489831665"]["snakefile"]["kwargs"])'
        )
    config:
        config["source1_1489831665"]["config"]
use rule * from source1_1489831665 as source1_1489831665_*

module sleep1_2066875522:
    snakefile:
        eval(
            f'{config["sleep1_2066875522"]["snakefile"]["function"]}'
            '(*config["sleep1_2066875522"]["snakefile"]["args"],'
            '**config["sleep1_2066875522"]["snakefile"]["kwargs"])'
        )
    config:
        config["sleep1_2066875522"]["config"]
use rule * from sleep1_2066875522 as sleep1_2066875522_*

module sleep2_1342243708:
    snakefile:
        eval(
            f'{config["sleep2_1342243708"]["snakefile"]["function"]}'
            '(*config["sleep2_1342243708"]["snakefile"]["args"],'
            '**config["sleep2_1342243708"]["snakefile"]["kwargs"])'
        )
    config:
        config["sleep2_1342243708"]["config"]
use rule * from sleep2_1342243708 as sleep2_1342243708_*

module sleep3_413855814:
    snakefile:
        eval(
            f'{config["sleep3_413855814"]["snakefile"]["function"]}'
            '(*config["sleep3_413855814"]["snakefile"]["args"],'
            '**config["sleep3_413855814"]["snakefile"]["kwargs"])'
        )
    config:
        config["sleep3_413855814"]["config"]
use rule * from sleep3_413855814 as sleep3_413855814_*

