configfile: "config/config.yaml"

module sleep3_a:
    snakefile:
        config["sleep3_a"]["snakefile"]
    config:
        config["sleep3_a"]["config"]
use rule * from sleep3_a as sleep3_a_*

module sleep3_b:
    snakefile:
        config["sleep3_b"]["snakefile"]
    config:
        config["sleep3_b"]["config"]
use rule * from sleep3_b as sleep3_b_*

module sleep3_c:
    snakefile:
        config["sleep3_c"]["snakefile"]
    config:
        config["sleep3_c"]["config"]
use rule * from sleep3_c as sleep3_c_*

