
rule nextclade:
    input:
        expand(
            "results/{indir}/{infile}",
            indir=config["input_namespace"],
            infile=config["input_filename"],
        ),
    output:
        expand(
            "results/{outdir}/{outfile}",
            outdir=config["output_namespace"],
            outfile=config["output_filename"],
        ),
    params:
        indataset="results/nextclade/data/sars-cov-2/",
        outdir=lambda w, input: os.path.splitext(input[0])[0],
    log:
        "logs/nextclade.log",
    benchmark:
        "benchmarks/nextclade.txt"
    conda:
        "envs/nextclade.yaml"
    shell:
        "nextclade run --in-order --output-all={params.outdir} --input-dataset {params.indataset} {input}"
