input_namespace:
  _sleep1: in
output_namespace: sleep2_1113178669
sleep1:
  config:
    input_filename: touch
    input_namespace: in
    output_filename: touch
    output_namespace: sleep1
    sleeptime: 1
  name: sleep1
  snakefile: /Users/jsb/repos/jsbrittain/snakeshack/workflows/Examples/modules/sleep/workflow/Snakefile
  type: module
sleep1_1140030832:
  config:
    input_filename: touch
    input_namespace: sleep2_1009769806
    output_filename: touch
    output_namespace: sleep1_1140030832
    sleeptime: 1
  name: sleep1
  snakefile: /Users/jsb/repos/jsbrittain/snakeshack/workflows/Examples/modules/sleep/workflow/Snakefile
  type: module
sleep1_2037318421:
  config:
    input_filename: touch
    input_namespace: sleep2
    output_filename: touch
    output_namespace: sleep1_2037318421
    sleeptime: 1
  name: sleep1
  snakefile: /Users/jsb/repos/jsbrittain/snakeshack/workflows/Examples/modules/sleep/workflow/Snakefile
  type: module
sleep2:
  config:
    input_filename: touch
    input_namespace: sleep1
    output_filename: touch
    output_namespace: sleep2
    sleeptime: 2
  name: sleep2
  snakefile: /Users/jsb/repos/jsbrittain/snakeshack/workflows/Examples/modules/sleep/workflow/Snakefile
  type: module
sleep2_1009769806:
  config:
    input_filename: touch
    input_namespace: sleep1_2037318421
    output_filename: touch
    output_namespace: sleep2_1009769806
    sleeptime: 2
  name: sleep2
  snakefile: /Users/jsb/repos/jsbrittain/snakeshack/workflows/Examples/modules/sleep/workflow/Snakefile
  type: module
sleep2_1113178669:
  config:
    input_filename: touch
    input_namespace: sleep1_1140030832
    output_filename: touch
    output_namespace: sleep2_1113178669
    sleeptime: 2
  name: sleep2
  snakefile: /Users/jsb/repos/jsbrittain/snakeshack/workflows/Examples/modules/sleep/workflow/Snakefile
  type: module
