configfile : "config/config.yaml"

rule extract_gisaid_by_seq_name:
    input:
        seqids=expand(
            "results/{indir}/{infile}",
            indir=config["input_namespace"]["seqids"],
            infile=config["input_filename"]["seqids"],
        ),
        gisaid=expand(
            "results/{indir}/{infile}",
            indir=config["input_namespace"]["gisaid"],
            infile=config["input_filename"]["gisaid"],
        ),
    output:
        expand(
            "results/{indir}/{infile}",
            indir=config["output_namespace"],
            infile=config["output_filename"],
        ),
    log:
        "logs/extract_gisaid_by_seq_name.log",
    benchmark:
        "benchmarks/extract_gisaid_by_seq_name.txt"
    conda:
        "envs/extract_gisaid_by_seq_name.yaml"
    shell:
        "workflow/scripts/extract_gisaid_metadata_by_seq_name/extract_gisaid_metadata_by_seq_name.sh -i {input.seqids} -m {input.gisaid} -o {output}"
